[package]
name = "p3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.2"

[[bin]]

name = "p3"
path = "src/main.rs"


[[bin]]

name = "test"
path = "src/test.rs"
